-- real_estate_articles 테이블 스키마
create table if not exists public.real_estate_articles (
  articleno bigint generated by default as identity primary key,
  articlename text not null,
  realestatetypename text not null,
  tradetypename text not null,
  floorinfo text,
  dealorwarrantprc text,
  direction text,
  articleconfirmymd text,
  articlefeaturedesc text,
  buildingname text,
  realtorname text,
  cppcarticleurl text,
  created_at timestamptz not null default now(),
  "isPopular" boolean not null default false
);
